### ISSUE TITLE
Cannot find "sql/relations.sql" in next.js setup

### ISSUE THREAD

**Issue by bjoernwuest** [mmkal/slonik-tools#424]
Hi,

first let me thank you for PGKit, which I think is a major improvement over the clumsiness of Slonik.

I use PGKit in a next.js setup. When starting the app, I get the following error (projectroot is a lengthy path I have replaced):

```
Error: Error reading file sql/relations.sql from <projectroot>/.next/queries/vendor-chunks: Error: ENOENT: no such file or directory, open '<projectroot>/.next/queries/vendor-chunks/sql/relations.sql'
  at eval (webpack-internal:///(rsc)/./node_modules/@pgkit/schemainspect/dist/misc.js:88:19)
  at eval (webpack-internal:///(rsc)/./node_modules/@pgkit/schemainspect/dist/pg/obj.js:68:29)
  at (rsc)/./node_modules/@pgkit/schemainspect/dist/pg/obj.js (<projectroot>/.next/server/vendor-chunks/@pgkit.js:290:1)
  at __webpack_require__ (<projectroot>/.next/server/webpack-runtime.js:33:43)
  at eval (webpack-internal:///(rsc)/./node_modules/@pgkit/schemainspect/dist/pg/index.js:17:14)
  at (rsc)/./node_modules/@pgkit/schemainspect/dist/pg/index.js (<projectroot>/.next/server/vendor-chunks/@pgkit.js:280:1)
  at __webpack_require__ (<projectroot>/.next/server/webpack-runtime.js:33:43)
```

Here is the relevant code triggering the error:

```
log.info(`Run data base migrations located in ${process.cwd() + cfs.migrationPath}.`);
const migrator = new Migrator({
    migrationTableName: "__pgMigrations",
    migrationsPath: process.cwd() + cfs.migrationPath,
    client: databaseClientRef.value,
});
const migrations = await migrator.up();
```

The next.config file looks as following. The webpack section had to be added because I use sshtunnel to connect to Postgres.
```
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        instrumentationHook: true,
    },
    webpack: (config, context) => {
        config.module.rules.push({
            test: /\.node$/,
            loader: "node-loader",
        });
        return config;
    },
};

export default nextConfig;
```

Unfortunately, I could not find a workaround, neither figure out how to include the "relations.sql" in the right folder since it is in the "node_modules" directory. Any help appreciated.

**Comment by mmkal** [comment]
I'll look into this - it sounds like schemainspect is running too eagerly. But even with that fixed it might be tricky to run via nextjs since that bundles the JavaScript even on the server side and so would need to copy the sql migration files manually. 

It's a scenario I want to officially support but might take a little time.

**Comment by mmkal** [comment]
SQL queries are now inlined so how you bundle shouldn't affect anything anymore, try the latest version and this problem should go away (at time of writing 0.2.3).

I'll close this, but:

- feel free to comment and I can reopen if you get the same issue
- you might see _other_ issues, because next.js builds your files into `.next` directory so your migrations path etc. might get messed up between dev and prod
